codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%   # Permitir hasta 1% de baja
    patch:
      default:
        target: 80%     # Cada PR debe cubrir al menos 80% del código nuevo

comment:
  layout: "reach, diff, files"
  require_changes: true
  branches:
    - master
    - develop
