// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Dynamo is an autogenerated mock type for the Dynamo type
type Dynamo struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, table, id, out
func (_m *Dynamo) Get(ctx context.Context, table string, id string, out interface{}) error {
	ret := _m.Called(ctx, table, id, out)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = rf(ctx, table, id, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: ctx, table, data
func (_m *Dynamo) Set(ctx context.Context, table string, data interface{}) error {
	ret := _m.Called(ctx, table, data)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, table, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDynamo creates a new instance of Dynamo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dynamo {
	mock := &Dynamo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
