package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.79

import (
	"context"

	"github.com/csolarz/graphql-server/graph/model"
)

// CreatePayment is the resolver for the createPayment field.
func (r *mutationResolver) CreatePayment(ctx context.Context, input model.NewPayment) (*model.Payment, error) {
	return r.Service.CreatePayment(ctx, input)
}

// Payments is the resolver for the payments field.
func (r *queryResolver) Payments(ctx context.Context) (*model.Payment, error) {
	return r.Service.Payments(ctx)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) (*model.User, error) {
	return r.Service.Users(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
