// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock

import (
	context "context"

	entities "github.com/csolarz/graphql-server/entities"
	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetLoan provides a mock function with given fields: ctx, loanID
func (_m *Usecase) GetLoan(ctx context.Context, loanID int64) (*entities.Loan, error) {
	ret := _m.Called(ctx, loanID)

	if len(ret) == 0 {
		panic("no return value specified for GetLoan")
	}

	var r0 *entities.Loan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Loan, error)); ok {
		return rf(ctx, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Loan); ok {
		r0 = rf(ctx, loanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Loan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLoan provides a mock function with given fields: ctx, request
func (_m *Usecase) NewLoan(ctx context.Context, request entities.LoanRequest) (*entities.Loan, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for NewLoan")
	}

	var r0 *entities.Loan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.LoanRequest) (*entities.Loan, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.LoanRequest) *entities.Loan); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Loan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.LoanRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUser provides a mock function with given fields: ctx, request
func (_m *Usecase) NewUser(ctx context.Context, request entities.UserRequest) (*entities.User, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for NewUser")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserRequest) (*entities.User, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.UserRequest) *entities.User); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.UserRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
