// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPayment struct {
	Amount float64 `json:"amount" dynamodbav:"amount"`
	UserID int64   `json:"user_id" dynamodbav:"user_id"`
}

type Payment struct {
	ID     int64   `json:"id" dynamodbav:"id"`
	Amount float64 `json:"amount" dynamodbav:"amount"`
	User   *User   `json:"user" dynamodbav:"user"`
}

type Query struct {
}

type User struct {
	ID   int64  `json:"id" dynamodbav:"id"`
	Name string `json:"name" dynamodbav:"name"`
}
