// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPayment struct {
	Amount float64 `json:"amount"`
	UserID string  `json:"user_id"`
}

type Payment struct {
	ID     string  `json:"id"`
	Amount float64 `json:"amount"`
	User   *User   `json:"user"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
